config/routes.rb
Rails.application.routes.draw do
  resources :posts
  get 'dashboards/index', as: :dashboards
	# resources :dashboards, only: %i[index posts] 
	resources :logins, only: %i[new create]
	resources :registrations, only: %i[new create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	validates :email, presence: true
	validates :password, presence: true

	has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
		user = User.find_by(id: session[:user_id])
		redirect_to new_login_path unless user
		@posts = user.posts
  end
	
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
		user = User.find_by(id: session[:user_id])
		redirect_to dashboards_path if user
		@user = User.new
  end

  def create
		@user = User.find_by(login_params)

		if @user
			session[:user_id] = @user.id
			redirect_to dashboards_path
		else 
			flash[:alert] = "Email or Password wrong"
			render :new, status: :unprocessable_entity
		end
  end

	private

		def login_params
			params.require(:user).permit(:email, :password)
		end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_post, only: %i[ show edit update destroy ]

	def index
		@posts = Post.all
	end

	def show
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(posts_params)
		@post.user_id = session[:user_id] if session.present?

		if @post.save
			redirect_to dashboards_path
		else
			flash[:alert] = "Couldn't create the post"
			render :new, status: :unprocessable_entity
		end
	end

	def edit
	end

	def update
		if @post.update(posts_params)
			redirect_to dashboards_path, notice: "Post was successfully updated."
		else
			 flash[:alert] = "Something wrong while updating your post"
			 render :edit, status: :unprocessable_entity
		end 
	end

	private
		def set_post
			@post = Post.find(params[:id])
		end

		def posts_params
			params.require(:post).permit(:title, :body)
		end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
		user = User.find_by(id: session[:user_id])
		redirect_to dashboards_path if user
		@user = User.new
  end

  def create
		@user = User.new(user_params)

		if @user.save
			redirect_to new_login_path
		else
			flash[:alert] = "Couldn't save the user"
			render :new, status: :unprocessable_entity
		end
  end

	private

		def user_params
			params.require(:user).permit(:email, :password)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def is_logged?
		session[:user_id].presence
	end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/dashboards/index.html.erb
<div class="w-full max-w-lg mx-auto">
	<h1 class="text-2xl font-semibold">This is the list of your posts</h1>

	<% @posts.each do |post| %>
		<div class="pb-3 mb-3 border-b border-gray-500">
			<header class="mb-4">
				<h3 class="text-lg">
					<%= link_to post.title, post_path(post.id), class: "underline" %>
				</h3>
				<em>by <%= post.user.email %></em>
			</header>

			<section class="mb-4">
				<%= post.body.truncate(160) %>
			</section>

			<footer>
				<%= link_to "Edit", edit_post_path(post.id), class: "px-4 py-2 bg-emerald-800 text-white" %>
			</footer>
		</div> 
	<% end if @posts.presence %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Auth</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-300">
		<header class="w-full h-full max-w-2xl mx-auto mb-5">
			<ul class="flex justify-start">
				<li class="mr-5 underline">
					<%= link_to "All Posts", posts_path %>
				</li>

				<% if is_logged? %>
					<li class="mr-5 underline">
						<%= link_to "Your Posts", dashboards_path %>
					</li>

					<li class="mr-5 underline">
						<%= link_to "New Post", new_post_path %>
					</li>
				<% else %>
					<li class="mr-5 underline">
						<%= link_to "Log In", new_login_path %>
					</li>

					<li class="mr-5 underline">
						<%= link_to "Register", new_registration_path %>
					</li>
				<% end %>
			</ul>
		</header>
		<main class="w-full h-full max-w-2xl mx-auto">
			<div class="flash">
				<div class="notice"><%= notice %></div>
				<div class="alert"><%= alert %></div>
			</div>
			<%= yield %>
		</main>
  </body>
</html>

app/views/logins/create.html.erb
<h1>Logins#create</h1>
<p>Find me in app/views/logins/create.html.erb</p>

app/views/logins/new.html.erb
<h1>Log in</h1>

<div class="w-full max-w-xs mx-auto">
	<%= form_with model: @user, url: logins_path, class: "bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4" do |form| %>
		<div class="mb-4">
			<%= form.label :email, class: "block text-gray-700 text-sm font-bold mb-2" %>
			<%= form.email_field :email, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
		</div>
		
		<div class="mb-4">
			<%= form.label :password, class: "block text-gray-700 text-sm font-bold mb-2" %>
			<%= form.password_field :password, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
		</div>

		<div class="mb-4">
			<%= form.submit "Log in", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
		</div>
	<% end %>
</div>

app/views/posts/edit.html.erb
<div class="w-full max-w-lg mx-auto">
	<h1 class="text-2xl font-semibold">Edit your post</h1>

	<%= form_with model: @post, class: "bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4" do |form| %>
		<div class="mb-4">
			<%= form.label :title, class: "block text-gray-700 text-sm font-bold mb-2" %>
			<%= form.text_field :title, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
		</div>

		<div class="mb-4">
			<%= form.label :body, class: "block text-gray-700 text-sm font-bold mb-2" %>
			<%= form.text_area :body, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
		</div>

		<div class="mb-4">
			<%= form.submit "Save Post", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
		</div>
	<% end %>
</div>

app/views/posts/index.html.erb
<div class="w-full max-w-lg mx-auto">
	<h1 class="text-2xl font-semibold">All the posts</h1>

	<% if @posts.present? %>
		<ul>
			<% @posts.each do |post| %>
				<div class="pb-3 mb-3 border-b border-gray-500">
					<header class="mb-4">
						<h3 class="text-lg">
							<%= link_to post.title, post_path(post.id), class: "underline" %>
						</h3>
						<em>by <%= post.user.email %></em>
					</header>

					<section class="mb-4">
						<%= post.body.truncate(160) %>
					</section>
				</div>
			<% end %>
		</ul>
	<% end %>
</div>

app/views/posts/new.html.erb
<div class="w-full max-w-lg mx-auto">
	<h1 class="text-2xl font-semibold">Create your post</h1>

	<%= form_with model: @post, class: "bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4" do |form| %>
		<div class="mb-4">
			<%= form.label :title, class: "block text-gray-700 text-sm font-bold mb-2" %>
			<%= form.text_field :title, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
		</div>

		<div class="mb-4">
			<%= form.label :body, class: "block text-gray-700 text-sm font-bold mb-2" %>
			<%= form.text_area :body, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
		</div>

		<div class="mb-4">
			<%= form.submit "Save Post", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
		</div>
	<% end %>
</div>

app/views/posts/show.html.erb
<div class="w-full max-w-lg mx-auto">
	<h1 class="text-2xl font-semibold"><%= @post.title %></h1>
	<section>
		<%= @post.body %>
	</section>
</div>